#!/usr/bin/env python3
"""Snapshot spytial's public authoring surface, for release-time diffing.

    python3 scripts/generate_api_baseline.py

Most of what a spytial user writes -- which decorators exist, which keyword
each accepts, which values each keyword takes -- is now derived from
spytial-core's language manifest rather than written out by hand. That is what
keeps it honest, but it also means the public API can change without anyone
editing a line of Python: a core release lands, the generator runs, and the
surface users program against is different.

This records that surface so the change is visible at release time. The
baseline lives at ``test/api_baseline.json`` and is compared by
``test/test_api_baseline.py``, which classifies every difference:

* **additive** -- a new form, a new optional keyword, a new accepted value, a
  keyword that stopped being required. Existing user code keeps working.
* **breaking** -- a form or keyword that disappeared, a keyword that became
  required, a value that stopped being accepted, a form that moved between the
  constraints and directives sections. Existing user code stops working, or
  starts producing a different diagram.

Regenerating the baseline is how a change gets acknowledged, and the regenerated
file records the spytial version that made it -- so `git log` over this one file
answers "when did the API change, and how" without reading the whole history.

``capture()`` is separate from ``main()`` so the test can build the current
surface without writing anything.
"""

from __future__ import annotations

import inspect
import json
import pathlib
from dataclasses import fields as dataclass_fields

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
BASELINE_PATH = REPO_ROOT / "test" / "api_baseline.json"

# Value vocabularies are part of the contract: a removed value breaks any spec
# that used it, and core would accept the removal silently.
VOCABULARY_NAMES = (
    "ALIGN_DIRECTIONS",
    "CONSTRAINT_HOLDS",
    "FLAG_NAMES",
    "GROUP_EDGE_DIRECTIONS",
    "ICON_PLACEMENTS",
    "LINE_PATTERNS",
    "ORIENTATION_DIRECTIONS",
    "ROTATION_DIRECTIONS",
    "TEXT_SIZES",
)


def _class_parameters(cls):
    """Keyword parameters of an ``Annotated[...]`` class, by requiredness.

    A class taking ``**kwargs`` (``Group``) is recorded as such: its accepted
    keys come from the field tables, which are captured separately, so spelling
    them out here would double-count.
    """
    signature = inspect.signature(cls.__init__)
    parameters = [
        p for name, p in signature.parameters.items() if name != "self"
    ]
    if any(p.kind is inspect.Parameter.VAR_KEYWORD for p in parameters):
        return "**kwargs"
    return {
        p.name: ("required" if p.default is inspect.Parameter.empty else "optional")
        for p in parameters
        if p.kind is not inspect.Parameter.VAR_KEYWORD
    }


def capture():
    """The current public authoring surface."""
    import spytial
    from spytial import _spec_tables as tables

    forms = {}
    for section, table in (
        ("constraints", tables.CONSTRAINT_TYPES),
        ("directives", tables.DIRECTIVE_TYPES),
    ):
        for name, spec in table.items():
            field_sets = spec if isinstance(spec, list) else [spec]
            forms[name] = {
                "section": section,
                "fieldSets": [
                    {
                        "required": sorted(field_set["required"]),
                        "optional": sorted(field_set["optional"]),
                    }
                    for field_set in field_sets
                ],
            }

    classes = {}
    for name in sorted(dir(spytial)):
        obj = getattr(spytial, name)
        if inspect.isclass(obj) and issubclass(obj, spytial.SpytialAnnotation):
            if obj is spytial.SpytialAnnotation:
                continue
            classes[name] = _class_parameters(obj)

    blocks = {}
    for block_name, block_cls in (
        ("textStyle", spytial.TextStyle),
        ("lineStyle", spytial.LineStyle),
        ("fillStyle", spytial.FillStyle),
        ("borderStyle", spytial.BorderStyle),
        ("iconStyle", spytial.IconStyle),
        ("groupEdge", spytial.GroupEdge),
    ):
        blocks[block_name] = sorted(f.name for f in dataclass_fields(block_cls))

    return {
        "_comment": (
            "Generated by scripts/generate_api_baseline.py. The public authoring "
            "surface as of the spytial version below. test_api_baseline.py fails "
            "when the live surface differs, classifying each difference as "
            "additive or breaking. Regenerate to acknowledge a deliberate change."
        ),
        "spytialVersion": spytial.__version__,
        "spytialCoreVersion": tables.CORE_VERSION,
        "languageVersion": tables.LANGUAGE_VERSION,
        "forms": dict(sorted(forms.items())),
        "vocabularies": {
            name: list(getattr(tables, name)) for name in VOCABULARY_NAMES
        },
        "blocks": blocks,
        "classes": classes,
        "exports": sorted(spytial.__all__),
    }


def render():
    return json.dumps(capture(), indent=2) + "\n"


def main():
    BASELINE_PATH.write_text(render(), encoding="utf-8")
    import spytial

    print(
        f"Wrote {BASELINE_PATH.relative_to(REPO_ROOT)} for spytial {spytial.__version__}."
    )


if __name__ == "__main__":
    main()
