#!/usr/bin/env python3
"""Record which spytial-core release each vendored artifact came from.

    python3 scripts/vendor_lock.py

spytial vendors four files out of the spytial-core npm tarball -- the language
manifest, the spec schema, the tier-2 evaluator bundle, and the conformance
harness bin -- and separately pins a version in ``spytial/core_assets.py`` that
decides which browser bundle is loaded from the CDN. All five have to be the
same release. A spec validated against one version of the language and rendered
by another is exactly the silent mismatch the vendoring exists to prevent; a
harness from one release checking specs written against another is that same
mismatch, in the one place meant to catch it.

The manifest, the schema, and the harness bin each state their own version, so
they can be checked directly. The evaluator bundle does not: it is a minified
build with no version string anywhere in it, so nothing about the file itself
says which release produced it. This lockfile is what makes that one checkable
-- it records the version and a content hash at vendor time, written by
``update-spytial-core.sh`` as part of the same step that copies the files.

The hash catches a file edited or replaced without re-vendoring; the version
catches a pin moved by hand without re-running the update script. The hash is
the stronger check even where a version string exists, so every vendored file
is recorded here, not only the one that has no other option.
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import re

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
LOCK_PATH = REPO_ROOT / "spytial" / "_vendor" / "VENDORED.json"
CORE_ASSETS = REPO_ROOT / "spytial" / "core_assets.py"

# Vendored artifact -> what it is, for the lockfile's own readability.
VENDORED_FILES = {
    "spytial/_vendor/spytial-language.json": "language manifest (drives _spec_tables.py)",
    "spytial/_vendor/spytial-spec.schema.json": "spec schema (validates emitted specs)",
    "spytial/suggest/_vendor/spytial-core-evaluator.js": "tier-2 evaluator bundle",
    # Test-only, so it lives under test/ and stays out of the wheel (MANIFEST.in
    # excludes test/). It is still vendored and locked like the rest: the point of
    # the harness is that it agrees with the release whose specs it is checking.
    "test/_vendor/spytial-check.js": "conformance harness bin (test/conformance.py)",
}


def pinned_version():
    """The spytial-core release ``core_assets.py`` pins."""
    match = re.search(
        r'SPYTIAL_CORE_VERSION = "([^"]+)"', CORE_ASSETS.read_text(encoding="utf-8")
    )
    if match is None:
        raise SystemExit("could not read SPYTIAL_CORE_VERSION from core_assets.py")
    return match.group(1)


def digest(path):
    return hashlib.sha256(pathlib.Path(path).read_bytes()).hexdigest()


def capture(version=None):
    """The lockfile contents for the current tree."""
    version = version or pinned_version()
    return {
        "_comment": (
            "Generated by scripts/vendor_lock.py via update-spytial-core.sh. "
            "Records which spytial-core release each vendored file came from and "
            "what it hashed to, so every one of them can be checked against the "
            "pin in core_assets.py -- including the evaluator bundle, which "
            "carries no version string of its own."
        ),
        "spytialCoreVersion": version,
        "files": {
            name: {"sha256": digest(REPO_ROOT / name), "role": role}
            for name, role in sorted(VENDORED_FILES.items())
        },
    }


def render(version=None):
    return json.dumps(capture(version), indent=2) + "\n"


def main():
    LOCK_PATH.write_text(render(), encoding="utf-8")
    print(f"Wrote {LOCK_PATH.relative_to(REPO_ROOT)} (spytial-core {pinned_version()}).")


if __name__ == "__main__":
    main()
